add_padding: true
check_correctness: true
device: cuda:1
evaluate_rotation_effect: true
generate_images: true
path_to_btcv: /media/ssd-3t-2/arkhipov/data/med/btcv/Abdomen/RawData/Training
path_to_meta: split_meta.json
path_to_model_checkpoint: UNETR_model_best_acc.pth
path_to_output: data/1_5
random_state: 43
run_name: add_metrics
use_wandb: false

border: -1
batch_size: 100
n_rotations: 101
angle_range:
- 1
- 5
