add_padding: true
check_correctness: true
device: cuda:1
evaluate_rotation_effect: true
generate_images: false
image_rotation_mode: bilinear
label_rotation_mode: nearest
path_to_btcv: /media/ssd-3t-2/arkhipov/data/med/btcv/Abdomen/RawData/Training
path_to_meta: split_meta.json
path_to_model_checkpoint: UNETR_model_best_acc.pth
path_to_output: data/0_0_135
random_state: 43
rotation_degrees:
- 0
- 0
- 135
run_name: remake
use_wandb: false
