add_padding: true
check_correctness: true
device: cuda:1
evaluate_rotation_effect: true
generate_images: false
path_to_btcv: /media/ssd-3t-2/arkhipov/data/med/btcv/Abdomen/RawData/Training
path_to_meta: split_meta.json
path_to_model_checkpoint: UNETR_model_best_acc.pth
path_to_output: data/0_0
random_state: 43
run_name: border=16
use_wandb: false

border: 16
batch_size: 100
n_rotations: 1
angle_range:
- 0
- 0
